// nginx/masz-svelte/src/components/nav/patchnotes/Patchnotes.svelte
<script lang="ts">
    import { OutboundLink } from "carbon-components-svelte";
    import { CheckmarkFilled, CircleSolid, LogoGithub, StarFilled, WarningFilled } from "carbon-icons-svelte";
    import moment from "moment";
    import type { Writable } from "svelte/store";
    import { writable } from "svelte/store";
    import MediaQuery from "../../../core/MediaQuery.svelte";
    import type { IPatchnote, IPatchnoteSeperator } from "../../../models/IPatchnote";
    import API from "../../../services/api/api";
    import { currentLanguage } from "../../../stores/currentLanguage";

    const patchnotes: Writable<Array<IPatchnote | IPatchnoteSeperator>> = writable([]);

    API.getStatic("/static/patchnotes.json").then((data: IPatchnote[]) => {
        const res = [{ text: "More coming..." }];
        for (let i = 0; i < data.length; i++) {
            res.push(data[i]);
            if (i + 1 < data.length - 1) {
                // calculate diff in days using moment
                if (data[i + 1].released_at) {
                    const diff = moment(data[i].released_at).diff(moment(data[i + 1].released_at), "days");
                    if (diff) {
                        res.push({
                            text: `${diff} days`,
                        });
                    }
                }
            }
        }
        patchnotes.set(res);
    });
</script>

<style>
    .contributors:hover > a {
        margin-right: 0.2rem;
    }
    .contributors > a {
        transform: scale(1);
        transition: 0.5s all ease;
    }
</style>

<MediaQuery query="(min-width: 1024px)" let:matches>
    <div class="flex flex-row items-center justify-center w-full">
        <div class="grid grid-cols-8 gap-0 w-full lg:w-1/2">
            {#each $patchnotes as patchnote}
                {#if patchnote.text}
                    {#if matches}
                        <div />
                    {/if}
                    <div
                        class="flex flex-row justify-center border-solid border-2 col-span-2 px-1 py-1" class:mx-4={matches}
                        style="border-color: #161616; color: var(--cds-text-05, #6f6f6f)">
                        <div class="">
                            {patchnote.text}
                        </div>
                    </div>
                    <div class="col-span-5" class:col-span-6={!matches} />
                {:else}
                    {#if matches}
                        <div
                            class="col-span-2 pb-8 pr-4"
                            style="color: var(--cds-text-05, #6f6f6f); padding-top: 2.6rem">
                            {patchnote.released_at != undefined
                                ? moment(patchnote.released_at).format($currentLanguage?.momentDateFormat ?? "DD/MM/YYYY")
                                : "Unknown"}
                        </div>
                    {:else}
                        <div />
                    {/if}
                    <div class="border-solid border-l-2 py-8 pl-4 col-span-6" class:col-span-7={!matches} style="border-color: #161616">
                        <div class="text-xl font-bold mb-4">{patchnote.version}</div>
                        {#if patchnote.contributors}
                            <div class="flex flex-row flex-wrap mb-4 contributors">
                                {#each patchnote.contributors as contributor}
                                    <a class="-mr-6" href={contributor.link} target="_blank">
                                        <img class="w-12 h-12 rounded-full" src={contributor.icon} alt={contributor.name} />
                                    </a>
                                {/each}
                            </div>
                        {/if}
                        <div class="grid grid-cols-8 gap-x-0 gap-y-4">
                            {#each patchnote?.breaking ?? [] as entry}
                                <div class="flex flex-row col-span-7">
                                    <div>
                                        <WarningFilled style="fill: var(--cds-support-error-inverse)" />
                                    </div>
                                    <div class="flex flex-col px-4">
                                        <div class="text-lg font-semibold">{entry.title}</div>
                                        <div>{entry.description}</div>
                                    </div>
                                </div>
                                <div class="pt-1">
                                    {#if entry.link}
                                        <OutboundLink href={entry.link}>Link</OutboundLink>
                                    {/if}
                                </div>
                            {/each}
                            {#each patchnote?.features ?? [] as entry}
                                <div class="flex flex-row col-span-7">
                                    <div>
                                        <StarFilled style="fill: var(--cds-support-warning-inverse)" />
                                    </div>
                                    <div class="flex flex-col px-4">
                                        <div class="text-lg font-semibold">{entry.title}</div>
                                        <div>{entry.description}</div>
                                    </div>
                                </div>
                                <div class="pt-1">
                                    {#if entry.link}
                                        <OutboundLink href={entry.link}>Link</OutboundLink>
                                    {/if}
                                </div>
                            {/each}
                            {#each patchnote?.fixes ?? [] as entry}
                                <div class="flex flex-row col-span-7">
                                    <div>
                                        <CheckmarkFilled style="fill: var(--cds-support-success-inverse)" />
                                    </div>
                                    <div class="flex flex-col px-4">
                                        <div class="text-lg font-semibold">{entry.title}</div>
                                        <div>{entry.description}</div>
                                    </div>
                                </div>
                                <div class="pt-1">
                                    {#if entry.link}
                                        <OutboundLink href={entry.link}>Link</OutboundLink>
                                    {/if}
                                </div>
                            {/each}
                            {#each patchnote?.technical ?? [] as entry}
                                <div class="flex flex-row col-span-7">
                                    <div>
                                        <LogoGithub style="fill: var(--cds-support-info)" />
                                    </div>
                                    <div class="flex flex-col px-4">
                                        <div class="text-lg font-semibold">{entry.title}</div>
                                        <div>{entry.description}</div>
                                    </div>
                                </div>
                                <div class="pt-1">
                                    {#if entry.link}
                                        <OutboundLink href={entry.link}>Link</OutboundLink>
                                    {/if}
                                </div>
                            {/each}
                            {#each patchnote?.changes ?? [] as entry}
                                <div class="flex flex-row col-span-7">
                                    <div>
                                        <CircleSolid style="fill: #161616" />
                                    </div>
                                    <div class="flex flex-col px-4">
                                        <div>{entry}</div>
                                    </div>
                                </div>
                                <div class="pt-1">
                                    {#if entry.link}
                                        <OutboundLink href={entry.link}>Link</OutboundLink>
                                    {/if}
                                </div>
                            {/each}
                        </div>
                    </div>
                {/if}
            {/each}
        </div>
    </div>
</MediaQuery>

// nginx/MASZ/src/app/components/basic/patchnotes/patchnotes.component.ts
import { Component, OnInit } from '@angular/core';
import { ContentLoading } from 'src/app/models/ContentLoading';
import { PatchNote } from 'src/app/models/PatchNote';
import { ApiService } from 'src/app/services/api.service';

@Component({
  selector: 'app-patchnotes',
  templateUrl: './patchnotes.component.html',
  styleUrls: ['./patchnotes.component.css']
})
export class PatchnotesComponent implements OnInit {

  public patchnotes: ContentLoading<PatchNote[]> = { loading: true, content: [] };

  constructor(private api: ApiService) { }

  ngOnInit(): void {
    this.reload();
  }

  private reload() {
    this.patchnotes = { loading: true, content: [] };
    this.api.getSimpleData('/static/patchnotes.json', false).subscribe((data) => {
      this.patchnotes.content = data;
      this.patchnotes.loading = false;
    }, () => {
      this.patchnotes.loading = false;
    });
  }
}

<div style="height: 100px;"></div>
<div class="d-flex flex-column justify-content-center align-items-center">
    <div class="d-flex flex-column justify-content-center align-items-center w-50">
        <div class="mat-display-2 font-weight-bold">Patchnotes</div>
    </div>
    <div class="row align-items-left cw-75-100">
        <ng-container *ngIf="!this.patchnotes.loading">
            <ng-container *ngFor="let note of this.patchnotes.content" >
                <div class="flex-grow-1 d-flex p-2" [ngClass]="note?.gist_feature_link ? 'col-sm-12' : 'col-sm-6'">
                    <mat-card class="d-flex flex-row flex-grow-1">
                        <div *ngIf="note?.gist_feature_link" class="mr-4 align-self-center">
                            <mat-icon title="Featured release">star</mat-icon>
                        </div>
                        <div>
                            <mat-card-title class="mb-0">
                                <div class="mat-h1 mb-0 font-weight-bold">
                                    {{ note.version }}
                                </div>
                            </mat-card-title>
                            <mat-card-content>
                                <div *ngIf="note.released_at" class="mat-caption mb-2" style="color: grey; line-height: 12px" title="release date">
                                    <app-date-display [date]="note.released_at"></app-date-display>
                                </div>
                                <div *ngIf="!note.released_at" class="mat-caption mb-2" style="color: grey; line-height: 12px">
                                    Unknown release date
                                </div>
                                <div *ngIf="note?.gist_feature_link">
                                    <a class="mat-h2 mb-0 font-weight-bold" href="{{ note?.gist_feature_link }}" target="_blank" style="text-decoration: underline;">
                                        Patchnotes on GitHub
                                    </a>
                                </div>
                                <div *ngIf="note?.contributors">
                                    <div class="d-flex flex-row align-items-center mb-2">
                                        <span class="mat-h2 mb-0 font-weight-bold" style="color: #fc22a8">CONTRIBUTORS</span>
                                        <div class="flex-grow-1 mx-4" style="background-color: #fc22a8; height: 3px"></div>
                                    </div>
                                    <div class="d-flex flex-row flex-wrap mb-2 pl-4">
                                        <div class="pr-1 pb-1" *ngFor="let contributor of note?.contributors">
                                            <a href="{{ contributor.link }}" target="_blank">
                                                <img
                                                    width="32"
                                                    height="32"
                                                    src="{{ contributor.icon }}"
                                                    title="Contributor {{ contributor.name }}"
                                                    alt="Contributor {{ contributor.name }}"
                                                    class="rounded-circle"
                                                    onerror="this.src='/assets/img/default_profile.png';" />
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <div *ngIf="note.breaking">
                                    <div class="d-flex flex-row align-items-center mb-2">
                                        <span class="mat-h2 mb-0 font-weight-bold" style="color: #d81b0e">BREAKING</span>
                                        <div class="flex-grow-1 mx-4" style="background-color: #d81b0e; height: 3px"></div>
                                    </div>
                                    <ul class="mat-4 mb-2 pl-4" *ngFor="let change of note.breaking">
                                        <li class="pn-details">
                                            <div class="d-flex flex-row">
                                                <div class="pn-details-text">
                                                    <b>{{ change.title }} </b>
                                                    {{ change.description }}
                                                </div>
                                                <a href="{{ change.link }}" target="_blank" *ngIf="change.icon">
                                                    <mat-icon aria-hidden="false" aria-label="tune icon">{{ change.icon }}</mat-icon>
                                                </a>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                                <div *ngIf="note.features">
                                    <div class="d-flex flex-row align-items-center mb-2">
                                        <span class="mat-h2 mb-0 font-weight-bold" style="color: #43b581">FEATURES</span>
                                        <div class="flex-grow-1 mx-4" style="background-color: #43b581; height: 3px"></div>
                                    </div>
                                    <ul class="mat-h4 mb-2 pl-4" *ngFor="let change of note.features">
                                        <li class="pn-details">
                                            <div class="d-flex flex-row">
                                                <div class="pn-details-text">
                                                    <b>{{ change.title }} </b>
                                                    {{ change.description }}
                                                </div>
                                                <a href="{{ change.link }}" target="_blank" *ngIf="change.icon">
                                                    <mat-icon aria-hidden="false" aria-label="tune icon">{{ change.icon }}</mat-icon>
                                                </a>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                                <div *ngIf="note.fixes">
                                    <div class="d-flex flex-row align-items-center mb-2">
                                        <span class="mat-h2 mb-0 font-weight-bold" style="color: #faa61a">FIXES</span>
                                        <div class="flex-grow-1 mx-4" style="background-color: #faa61a; height: 3px"></div>
                                    </div>
                                    <ul class="mat-h4 mb-2 pl-4" *ngFor="let change of note.fixes">
                                        <li class="pn-details">
                                            <div class="d-flex flex-row">
                                                <div class="pn-details-text">
                                                    <b>{{ change.title }} </b>
                                                    {{ change.description }}
                                                </div>
                                                <a href="{{ change.link }}" target="_blank" *ngIf="change.icon">
                                                    <mat-icon aria-hidden="false" aria-label="tune icon">{{ change.icon }}</mat-icon>
                                                </a>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                                <div *ngIf="note.technical">
                                    <div class="d-flex flex-row align-items-center mb-2">
                                        <span class="mat-h2 mb-0 font-weight-bold" style="color: #00acc8">TECHNICAL</span>
                                        <div class="flex-grow-1 mx-4" style="background-color: #00acc8; height: 3px"></div>
                                    </div>
                                    <ul class="mat-h4 mb-2 pl-4" *ngFor="let change of note.technical">
                                        <li class="pn-details">
                                            <div class="d-flex flex-row">
                                                <div class="pn-details-text">
                                                    <b>{{ change.title }} </b>
                                                    {{ change.description }}
                                                </div>
                                                <a href="{{ change.link }}" target="_blank" *ngIf="change.icon">
                                                    <mat-icon aria-hidden="false" aria-label="tune icon">{{ change.icon }}</mat-icon>
                                                </a>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                                <div *ngIf="note.changes">
                                    <div class="d-flex flex-row align-items-center mb-2">
                                        <span class="mat-h2 mb-0">CHANGES</span>
                                        <div class="flex-grow-1 mx-4" style="background-color: white; height: 3px"></div>
                                    </div>
                                    <ul class="mat-h4 mb-2 pl-4" *ngFor="let change of note.changes">
                                        <li class="pn-details">
                                            {{ change }}
                                        </li>
                                    </ul>
                                </div>
                            </mat-card-content>
                        </div>
                    </mat-card>
                </div>
            </ng-container>
        </ng-container>
        <ng-container *ngIf="!this.patchnotes.loading && this.patchnotes.content?.length === 0">
            <img src="/assets/img/notfound.svg" class="w-50 align-self-center"/>
        </ng-container>
        <ng-container *ngIf="this.patchnotes.loading">
            <div>
                <div class="p-2">
                    <div class="mat-h2 waiting-for-text font-weight-bold" style="width: 200px;"></div>
                    <div class="mat-h3 mb-1 waiting-for-text" style="width: 500px;"></div>
                    <div class="mat-h3 waiting-for-text" style="width: 300px;"></div>
                </div>
            </div>
            <div>
                <div class="p-2">
                    <div class="mat-h2 waiting-for-text font-weight-bold" style="width: 200px;"></div>
                    <div class="mat-h3 mb-1 waiting-for-text" style="width: 500px;"></div>
                    <div class="mat-h3 waiting-for-text" style="width: 300px;"></div>
                </div>
            </div>
            <div>
                <div class="p-2">
                    <div class="mat-h2 waiting-for-text font-weight-bold" style="width: 200px;"></div>
                    <div class="mat-h3 mb-1 waiting-for-text" style="width: 500px;"></div>
                    <div class="mat-h3 waiting-for-text" style="width: 300px;"></div>
                </div>
            </div>
        </ng-container>
    </div>
</div>
